AWSTemplateFormatVersion: '2010-09-09'
Description: 'Initialize Resources for NCTU BBS'
Resources:
    ContainerRepository:
        Type: AWS::ECR::Repository
        Properties: 
            RepositoryName: nctu-np-bbs

    SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties: 
            GroupDescription: SecurityGroup For NCTU BBS
            GroupName: NCTU_BBS_SG
            SecurityGroupIngress: 
                - IpProtocol: tcp
                  FromPort: 3000
                  ToPort: 3000
                  CidrIp: 0.0.0.0/0
            VpcId: vpc-828f49fa

    FargateCluster:
        Type: AWS::ECS::Cluster
        Properties: 
            ClusterName: NCTU-BBS-Cluster

    S3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: oscarhsu-nctu-bbs

    CognitoUserPool:
        Type: AWS::Cognito::UserPool
        Properties:
            UserPoolName: nctu-bbs-user-pool
            Policies:
                PasswordPolicy:
                    MinimumLength: 8
                    RequireLowercase: false
                    RequireNumbers: false
                    RequireSymbols: false
                    RequireUppercase: false
                    TemporaryPasswordValidityDays: 365
